---
driver:
  name: lxd_cli

## faster transfer time
transport:
  name: sftp

## https://github.com/simonmcc/kitchen-salt/blob/master/provisioner_options.md
provisioner:
  name: salt_solo
## only from dir above sift
#  formula: sift
## OK
  state_collection: true
  collection_name: sift
  state_top:
    base:
      '*':
        - sift

platforms:
  - name: ubuntu-16.04
#  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:

