FROM ubuntu:16.04
RUN apt-get update

RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils python-software-properties software-properties-common git wget
RUN wget -O /tmp/SALTSTACK-GPG-KEY.pub https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
RUN apt-key add /tmp/SALTSTACK-GPG-KEY.pub
RUN echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" >> /etc/apt/sources.list.d/saltstack.list
RUN apt-get update
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y -o DPkg::Options::=--force-confold salt-ssh

